/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: aoyi1                                                 *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmaoyi1;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsaoyi1[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palaoyi1 = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acaoyi1[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, XX______, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ________, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _______X, XXXXXXXX, XXXXX___, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX, XXXXXXXX, X_______, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX,
  XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX,
  XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX,
  XXXXXXXX, XXXX___X, XXX_____, _XXXXXXX, XXXXXXX_, _____XXX, X___XXXX, XXXXXXXX,
  XXXXXXXX, XXXX___X, XX______, __XXXXXX, XXXXXX__, ___X___X, X___XXXX, XXXXXXXX,
  XXXXXXXX, XXXX___X, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___X_XX, XXXXXXXX,
  XXXXXXXX, X__XX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__XXX_X, XXXXXXXX,
  XXXXXXXX, XXX_X__X, XXXX____, __XXXXXX, XXXXXX__, ____XXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, X_XXX__X, XX____X_, _X_XXXXX, XXXXX_X_, _X___XXX, X___XX_X, XXXXXXXX,
  XXXXXXXX, X_XXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__XXX_X, XXXXXXXX,
  XXXXXXXX, XX_XX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXX_XX, XXXXXXXX,
  XXXXXXXX, XX_XXX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X__XX_XX, XXXXXXXX,
  XXXXXXXX, XX_XXX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXX_XX, XXXXXXXX,
  XXXXXXXX, XX_XXX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX,
  XXXXXXXX, XXX_XX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XX_XXX, XXXXXXXX,
  XXXXXXXX, XXX_XX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XX_XXX, XXXXXXXX,
  XXXXXXXX, XXXX_XX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XX_XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__X_, XXXXXXXX, XXXXX__X, X__X_XXX, XXXXXXXX, _X_XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXXXXXX, XXXX___X, ____XXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, _XXXXXXX, X______X, _______X, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XX______, ______XX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX_X__XX, XXXXXXXX, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XX__X, XXXXXXXX, XXXXXXXX, X__X__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXX__, XXXXXXXX, XXXXXXXX, ___XX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, _XXXXXX_, _XXXXXXX, XXXXXX__, _XXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, ___XXXXX, XXXXX___, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _XXXXXXX, XX____XX, XXX___XX, XXXXXX__, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, _XXXXXXX, XXXX____, _____XXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX,
  XXXXXXXX, X_______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _______X, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmaoyi1 = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acaoyi1,  // Pointer to picture data (indices)
  &_Palaoyi1   // Pointer to palette
};

/*************************** End of file ****************************/
