/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: zyx3                                                  *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmzyx3;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorszyx3[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palzyx3 = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _aczyx3[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, __X__XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ______X_, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ____XXXX, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ____XXXX, X_X_____, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ___XXXXX, XXXXX___, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, __XXXXXX, XXXXXX__, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, _XXXXXXX, XXXXXXX_, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, XXXXXXXX, XXXXXXX_, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXX_____, _____XXX, XXXXXXXX, XXXXXXXX, XX______, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, _____XXX, XXXXXXXX,
  XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _____XXX, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ______XX, XXXXXXXX,
  XXXXXXXX, X______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ______XX, XXXXXXXX,
  XXXXXXXX, X_____XX, XXXX____, _XXXXXXX, XXXXXXXX, ____XXXX, ______XX, XXXXXXXX,
  XXXXXXXX, X_____XX, XX______, __XXXXXX, XXXXX___, ______XX, ______XX, XXXXXXXX,
  XXXXXXXX, XX____XX, ____XXXX, X__XXXXX, XXXXX_XX, XXXX___X, ______XX, XXXXXXXX,
  XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, XX______, _XXXXXXX, XXXXXX__, ____XXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XX______, __XXXXXX, XXXX____, _____XXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXX___, X_XXXXXX, XXXX____, __X___XX, X_____XX, XXXXXXXX,
  XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX,
  XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XX_XXXXX, XXXXXXXX, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXX____X, XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXX_, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXXXXXX, XXXX__XX, X_XXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXXXXXX, XXXX__XX, ___XXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XX_____X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XX______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, X_______, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, X_______, _XXXXXXX, XX__XXX_, _X__XXXX, XXXXX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, X_______, _XXXXXXX, X_______, ______XX, XXXXX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX,
  XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XX______, ___XXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XX______, ___XXXXX, XXXXXXXX,
  XXXXXXXX, ________, _____XXX, XXXXXXXX, XXXXXXXX, XX______, _____XXX, XXXXXXXX,
  XXXXXXXX, ________, ______XX, XXXXXXXX, XXXXXXXX, X_______, ______XX, XXXXXXXX,
  XXXXX___, ________, ______XX, XXXXXXXX, XXXXXXXX, ________, ________, XXXXXXXX,
  XX______, ________, _______X, XXXXXXXX, XXXXXXX_, ________, ________, _XXXXXXX,
  ________, ________, ________, _XXXXXXX, XXXXX___, ________, ________, __XXXXXX,
  ________, ________, ________, __XXXXXX, XXXX____, ________, ________, __XXXXXX,
  ________, ________, ________, ____XXXX, XXX_____, ________, ________, XXXXXXXX,
  ________, ________, ________, ________, ________, ________, ________, _XXXXXXX,
  ________, ________, ________, ________, ________, ________, ________, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmzyx3 = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _aczyx3,  // Pointer to picture data (indices)
  &_Palzyx3   // Pointer to palette
};

/*************************** End of file ****************************/
